/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  BigNumberish,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { BasicContract } from "../BasicContract";

export class BasicContract__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _init: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BasicContract> {
    return super.deploy(_init, overrides || {}) as Promise<BasicContract>;
  }
  getDeployTransaction(
    _init: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_init, overrides || {});
  }
  attach(address: string): BasicContract {
    return super.attach(address) as BasicContract;
  }
  connect(signer: Signer): BasicContract__factory {
    return super.connect(signer) as BasicContract__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BasicContract {
    return new Contract(address, _abi, signerOrProvider) as BasicContract;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_init",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_num",
        type: "uint256",
      },
    ],
    name: "setNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516101213803806101218339818101604052602081101561003357600080fd5b8101908080519060200190929190505050806000819055505060c78061005a6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80633fb5c1cb146037578063f2c9ecd8146062575b600080fd5b606060048036036020811015604b57600080fd5b8101908080359060200190929190505050607e565b005b60686088565b6040518082815260200191505060405180910390f35b8060008190555050565b6000805490509056fea2646970667358221220e5c09d26112cb535b948996538d28f39116107275e5b90c9f9e1bb4d5476ef6564736f6c63430007030033";
